---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update package cache (Debian)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"
      changed_when: false
