---
- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Start and enable firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true

- name: Open Tomcat port on firewall
  ansible.posix.firewalld:
    port: "{{ tomcat_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
